title: Ashwattha Phatak
logo: assets/iimg/84adae99-ec24-49af-ac6b-23e4fc266887.JPG

description: |
  I am a Computer Science student at North Carolina State University with a passion for exploring the frontiers of technology.  
  With experience as a Site Reliability Engineer and a solid foundation in Computer Vision, Machine Learning, and Operating Systems, I am eager to drive innovations in autonomous vehicles and system-level software.  
  My curiosity fuels my commitment to staying updated with the latest advancements in tech, constantly seeking opportunities to learn and contribute to cutting-edge solutions.  

  Beyond my professional aspirations, I am an avid soccer, cricket, and Formula 1 fan, as well as a passionate trekker and traveler, always eager to explore new places and perspectives.  
  I believe in combining creativity, collaboration, and technical expertise to make a meaningful impact.  
  I am actively seeking tech internships across the US to further develop my skills and contribute to transformative projects. Let’s connect and create something extraordinary together!  

show_downloads: true
theme: jekyll-theme-minimal

social_links:  
  - name: GitHub  
    url: https://github.com/AshP-dev  
    icon: fab fa-github  
  - name: LinkedIn  
    url: https://linkedin.com/in/ashwatthaphatak  
    icon: fab fa-linkedin  
  - name: Email  
    url: mailto:ashwatthap@gmail.com  
    icon: fas fa-envelope  
 

