title: Ashwattha Phatak
logo: /assets/iimg/DSC_0826.JPG

description: I am a Computer Science student at North Carolina State University with a passion technology and system reliability. With experience as a Site Reliability Engineer and a solid background in Computer Vision, I offer a unique blend of skills and expertise. I am actively seeking tech internships across the US to harness my skills and gain more experience. Let us connect and work together to create impactful and cutting-edge solutions together!
show_downloads: true
theme: jekyll-theme-minimal

