title: Ashwattha Phatak
logo: assets/iimg/84adae99-ec24-49af-ac6b-23e4fc266887.JPG

description: I am a Computer Science student at North Carolina State University with a passion for technology. With experience as a Site Reliability Engineer and a solid background in Computer Vision and Machine Learning, I offer a unique blend of skills and expertise. I am actively seeking tech internships across the US to harness my skills and gain more experience. Let us connect and work to create impactful and cutting-edge solutions together!
show_downloads: true
theme: jekyll-theme-minimal

