---
title: Ashwattha Phatak
logo: assets/iimg/84adae99-ec24-49af-ac6b-23e4fc266887.JPG

description: >
  <strong>I am a Computer Science student at North Carolina State University with a passion for exploring the frontiers of technology.</strong><br/>
  With experience as a <strong>Site Reliability Engineer</strong> and a solid foundation in <strong>Computer Vision, Machine Learning, and Operating Systems</strong>, I am eager to drive innovations in <strong>autonomous vehicles</strong> and <strong>system-level software</strong>.<br/>
  My curiosity fuels my commitment to staying updated with the latest advancements in tech, constantly seeking opportunities to learn and contribute to cutting-edge solutions.

show_downloads: true
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
