title: Ashwattha Phatak
logo: /assets/iimg/DSC_0826.JPG
description: I am a Computer Science student at North Carolina State University with a strong interest in technology and system reliability. With experience as a Site Reliability Engineer and a background in Computer Vision, I bring a unique blend of skills to the table. I am actively seeking tech internships in the US to apply my expertise and gain further experience in the field. Let us connect and work together to create resilient and innovative solutions!
show_downloads: true
theme: jekyll-theme-minimal

